= Mulesoft Developer Documentations Writing Style

This repository contains a https://github.com/errata-ai/vale[Vale-compatible] implementation of the Mulesoft Writing Style Guide, which is loosely based on the https://docs.microsoft.com/en-us/style-guide/welcome/[Microsoft Writing Style Guide^]. 
link:LICENSE[LICENSE]

The primary purpose of this repository is to enforce the writing style of the https://docs.mulesoft.com[Mulesoft Technical Documentation^]. It contains the style rules in the form of a series of yaml files, which are used by Vale to automatically lint the documentation content via Github actions.

## Getting Started

NOTE: ❗ Mulesoft Writing Style requires Vale >= **1.7.0**. ❗

In the root directory of your docs repo, create a file called *.vale.ini* with the following content:

```ini
StylesPath = ../dev-docs-writing-style
MinAlertLevel = suggestion

[modules/ROOT/pages/*.adoc]
BasedOnStyles = mulesoft
```

This is the file that tells Vale to use the Mulesoft Writing Style for all of your docs.

Then, create a directory named *.github/workflows*. Within this directory, create a file called *vale.yml* with the following content:

```yaml
name: Linting
on: [push]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Vale
      uses: errata-ai/vale-action@v1.7.0
      with:
        styles: |
          https://github.com/mulesoft/dev-docs-writing-style/releases/download/latest/mulesoft.zip
        debug: true
      env:
        # Required, set by GitHub actions automatically:
        # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

This creates a https://github.com/errata-ai/vale-action[Vale Github Action] that will automatically lint your docs.

== Resources

* https://docs.mulesoft.com/en/dev-docs/writing-style-guide/[Mulesoft Writing Style Guide]
* https://github.com/errata-ai/vale-action[Vale-action]
