= Mulesoft Developer Documentations Writing Style

This repository contains a https://github.com/errata-ai/vale[Vale-compatible] implementation of the Mulesoft Writing Style Guide, which is loosely based on the https://docs.microsoft.com/en-us/style-guide/welcome/[Microsoft Writing Style Guide^]. 
link:LICENSE[LICENSE]

The primary purpose of this repository is to enforce the writing style of the https://docs.mulesoft.com[Mulesoft Technical Documentation^]. It contains the style rules in the form of a series of yaml files, which are used by Vale to automatically lint the documentation content via Github actions.

## Getting Started

NOTE: ❗ Mulesoft Writing Style requires Vale >= **1.7.0**. ❗

There are a few files in the link:onboarding-files[onboarding-files] directory that are used to configure the style guide. They need to be copied over to your docs repo.

Simply run `cp -R onboarding-files/. <path>` where <path> is the path to your docs repo, for example `cp -R onboarding-files/. ../docs-anypoint-datagraph`.

== Resources

* https://docs.mulesoft.com/en/dev-docs/writing-style-guide/[Mulesoft Writing Style Guide]
* https://github.com/errata-ai/vale-action[Vale-action]
