name: CI

on:
  push:
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: mulesoft-ubuntu
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Asciidoctor
        run: sudo apt-get install -y asciidoctor

      - name: Install Vale
        run: |
          wget -O vale.tar.gz https://github.com/errata-ai/vale/releases/download/v3.12.0/vale_3.12.0_Linux_64-bit.tar.gz
          tar -xzf vale.tar.gz
          sudo mv vale /usr/local/bin/
          
      - name: Install yq (YAML processor)
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          
      - name: Make test script executable
        run: chmod +x test-files/tests.sh
        
      - name: Run Vale tests with validation
        run: make test
      
      - name: Zip MuleSoft folder
        run: |
          mkdir -p ./dist
          zip -r ./dist/MuleSoft.zip ./MuleSoft/
      
      - name: Create Github Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $(shell semver -i major $(curl -s https://api.github.com/repos/mulesoft/mulesoft-docs-writing-style/releases/latest | jq -r '.tag_name'))
          release_name: Release $(shell semver -i major $(curl -s https://api.github.com/repos/mulesoft/mulesoft-docs-writing-style/releases/latest | jq -r '.tag_name'))
          draft: false
          prerelease: false
          upload_assets: ./dist/MuleSoft.zip
